'use server';

import { ai } from '@/ai/genkit';
import { resolveOrganizationGeminiApiKey } from '@/lib/agent/organization-ai-keys';
import { z } from 'genkit';

const GenericTextGenerationInputSchema = z.object({
  promptText: z.string().describe('The prompt to generate text from.'),
  modelName: z.string().optional().describe('Optional Gemini model name.'),
  organizationId: z.string().optional().describe('Optional organization id to resolve the Gemini key.'),
  apiKeyId: z.string().optional().describe('Optional named Gemini key id configured for the organization.'),
  modelConfig: z.any().optional().describe('Optional model config, including apiKey overrides.'),
});
export type GenericTextGenerationInput = z.infer<typeof GenericTextGenerationInputSchema>;

const GenericTextGenerationOutputSchema = z.object({
  generatedText: z.string().describe('The text generated by the AI.'),
});
export type GenericTextGenerationOutput = z.infer<typeof GenericTextGenerationOutputSchema>;

export async function genericTextGenerationFlow(input: GenericTextGenerationInput): Promise<GenericTextGenerationOutput> {
  return definedGenericTextGenerationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'genericTextGenerationPrompt',
  input: { schema: GenericTextGenerationInputSchema },
  output: { schema: GenericTextGenerationOutputSchema },
  prompt: `{{{promptText}}}

Por favor, gere uma resposta para o prompt acima.`,
});

const definedGenericTextGenerationFlow = ai.defineFlow(
  {
    name: 'genericTextGenerationFlow',
    inputSchema: GenericTextGenerationInputSchema,
    outputSchema: GenericTextGenerationOutputSchema,
  },
  async (input) => {
    const resolvedApiKey = await resolveOrganizationGeminiApiKey({
      organizationId: input.organizationId,
      selectedKeyId: input.apiKeyId,
      legacyApiKey: input.modelConfig?.apiKey,
      modelName: input.modelName,
      provider: 'google',
    });

    const mergedModelConfig =
      input.modelConfig && typeof input.modelConfig === 'object'
        ? { ...input.modelConfig }
        : {};

    if (resolvedApiKey) {
      mergedModelConfig.apiKey = resolvedApiKey;
    }

    const { output } = await prompt(input, {
      model: input.modelName,
      config: Object.keys(mergedModelConfig).length > 0 ? mergedModelConfig : undefined,
    });

    if (!output) {
      console.error('[genericTextGenerationFlow] LLM did not return a valid output structure. Returning default reply.');
      return { generatedText: 'Desculpe, nao consegui gerar uma resposta no momento.' };
    }
    return output;
  }
);
